name: color
version: 2.0.2
description: A simple Dart package exposing a Color class which can be used to create, convert, alter, and compare colors.
authors:
- Michael Fenwick <mike@mikefenwick.com>
- Tim Kluge <timklge@wh2.tu-dresden.de>
homepage: http://github.com/MichaelFenwick/Color
dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
